// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Rxdb$Reasonbot = require("./Rxdb.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var dbName = "./reasonbot";

function createDb(cont) {
  Rxdb$Reasonbot.create(dbName).catch((function (err) {
            console.log("Failed to connect to DB: ./reasonbot");
            console.log(err);
            Curry._1(cont, undefined);
            return Promise.reject([
                        Caml_builtin_exceptions.failure,
                        "Db Creation Error!"
                      ]);
          })).then((function (v) {
          return Promise.resolve(Curry._1(cont, Caml_option.some(v)));
        }));
  return /* () */0;
}

exports.dbName = dbName;
exports.createDb = createDb;
/* Rxdb-Reasonbot Not a pure module */
