// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Bot$Reasonbot = require("./Bot.bs.js");

Bot$Reasonbot.createBot(undefined, (function (_bot) {
        console.log("Bot Created");
        return /* () */0;
      }));

/*  Not a pure module */
