// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Rxdb = require("rxdb");

((require('rxdb').plugin(require('pouchdb-adapter-memory'))));

function create(name) {
  return Rxdb.create({
              name: name,
              adapter: "memory"
            });
}

exports.create = create;
/*  Not a pure module */
