// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Bot$Reasonbot = require("../src/Bot.bs.js");
var TestHelper$Reasonbot = require("./TestHelper.bs.js");

TestHelper$Reasonbot.test("token is not empty", (function (param) {
        return TestHelper$Reasonbot.toBe(0, TestHelper$Reasonbot.not__(TestHelper$Reasonbot.expect(Bot$Reasonbot.token.length)));
      }));

TestHelper$Reasonbot.test("token is not empty", (function (param) {
        return TestHelper$Reasonbot.toBe(0, TestHelper$Reasonbot.not__(TestHelper$Reasonbot.expect(Bot$Reasonbot.token.length)));
      }));

TestHelper$Reasonbot.testAsync("bot constructs successfully", undefined, (function (cb) {
        Bot$Reasonbot.createBot(undefined, (function (_bot) {
                return Curry._1(cb, TestHelper$Reasonbot.pass);
              }));
        return /* () */0;
      }));

/*  Not a pure module */
